### ISSUE TITLE
Displays during COTD rounds when not playing COTD

### ISSUE THREAD

**Issue by ezio416** [DeafChips/tm-cotd-stats#2]
I joined the TOTD server after qualifications ended, but the window still displays as if I'm in the quali. I'm guessing it has something to do with COTD being ongoing and me being on the TOTD server.
<img width="191" alt="Screenshot 2023-10-29 202618" src="https://github.com/chipsTM/tm-cotd-stats/assets/37951898/48c3af87-13ed-4fcd-aa8b-96d7a6a34169">

**Comment by chipsTM** [comment]
Not really a bug, the server is still in COTD qualifications game mode after the first 15 minutes. Wait until server changes back to time attack daily game mode. Closing as most likely not going to fix
